In [1]:
import numpy as np

In [2]:
array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
array

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
array.shape

(9,)

In [5]:
array.ndim

1

In [8]:
array_mod = array.reshape(3,3)

In [9]:
array_mod

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [19]:
arr_transp = array_mod.transpose()

In [20]:
arr_transp

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [21]:
arr_plano = array_mod.flatten()

In [25]:
arr_plano

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
# ej 1

In [27]:
array_original = np.array([1,2,3,4,5,6,7,8,9,10,11,12])

In [28]:
array_reshape = array_original.reshape(3,4)

In [29]:
array_reshape

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [30]:
# ej 2

In [33]:
array_original2 = np.array([[1,2,3],[4,5,6]])

In [34]:
array_original2

array([[1, 2, 3],
       [4, 5, 6]])

In [35]:
array_modificado = array_original2.transpose()

In [36]:
array_modificado

array([[1, 4],
       [2, 5],
       [3, 6]])

In [37]:
# ej 3

In [40]:
array_aplanado = array_original2.flatten()

In [41]:
array_aplanado

array([1, 2, 3, 4, 5, 6])