In [1]:
import numpy as np

In [2]:
x = [1,2,3]
y = [1,2,3]
z = [1,2,3]

In [4]:
np.concatenate([x,y,z])

array([1, 2, 3, 1, 2, 3, 1, 2, 3])

In [12]:
a = [[1,2], [3,4]]
b = [[5,6], [7,8]]
np.concatenate([a,b], axis=1)

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [14]:
a = [[1,2], [3,4]]
b = [[5,6], [7,8]]
arr_concat = np.concatenate([a,b], axis=0)
arr_concat

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [15]:
arr_concat.shape

(4, 2)

In [18]:
arr_concat.reshape(2,4)

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [19]:
# ej 1

In [20]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([6,7,8,9,10])

In [22]:
arr_concat = np.concatenate([arr1, arr2])

In [23]:
arr_concat

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [28]:
# ej 2

In [26]:
arr_og = np.array([1,2,3,4,5,6])
arr_reshape = arr_og.reshape(2,3)

In [27]:
arr_reshape

array([[1, 2, 3],
       [4, 5, 6]])

In [29]:
# ej 3

In [30]:
A = np.array([[1,2], [3,4]])

In [32]:
B = np.array([[5,6], [7,8]])

In [34]:
Suma_AB = A + B
Suma_AB

array([[ 6,  8],
       [10, 12]])

In [36]:
Mult_AB = A * B
Mult_AB

array([[ 5, 12],
       [21, 32]])