In [1]:
import numpy as np

In [2]:
# permite arrays de N dimensiones

In [3]:
arr = np.array([1,2,3])

In [4]:
arr

array([1, 2, 3])

In [17]:
arr
# arr de una dimesnion

array([1, 2, 3])

In [16]:
arr_2d = np.array([[1,2,3], [4,5,6]])
arr_2d
# arr de dos dimensiones

array([[1, 2, 3],
       [4, 5, 6]])

In [13]:
arr_3d = np.array([])

C:\Users\Usuario\AppData\Local\Temp\ipykernel_15264\3001729944.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  arr_3d = np.array([[[1,2,3], [4,5,6]], [7,8,9]])
