In [1]:
import numpy as np

In [2]:
arr = np.array([1,2,3, np.nan, 5])

In [3]:
arr

array([ 1.,  2.,  3., nan,  5.])

In [4]:
np.isnan(arr)

array([False, False, False,  True, False])

In [7]:
np.nanmean(arr)

2.75

In [9]:
arr2 = np.where(np.isnan(arr), 0, arr)
arr2

array([1., 2., 3., 0., 5.])

In [16]:
prom = np.nanmean(arr)
arr2 = np.where(np.isnan(arr), np.ceil(prom), arr)
arr2

array([1., 2., 3., 3., 5.])

In [20]:
arr_filtr = arr[~np.isnan(arr)]
arr_filtr

array([1., 2., 3., 5.])

In [21]:
# ej 1

In [23]:
array = np.array([3, np.nan, 7, np.nan, 0, 4.5, np.nan])
np.isnan(array)

array([False,  True, False,  True, False, False,  True])

In [ ]:
# ej 2